select B.AUTHOR_ID, AUTHOR_NAME, B.CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
from BOOK as B
JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
group by AUTHOR_ID, CATEGORY
order by B.AUTHOR_ID, B.CATEGORY desc