-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
from REST_INFO RI
join (select max(FAVORITES) as MAX_FAVORITES, FOOD_TYPE from REST_INFO 
     group by FOOD_TYPE) as M
     on M.FOOD_TYPE = RI.FOOD_TYPE and M.MAX_FAVORITES = RI.FAVORITES
order by RI.FOOD_TYPE desc